"ChA_zph7aao":
  title: "Getting started"
  provider: "youtube"
  description: "GitHub Classroom automates repository creation and access control, making it easy to distribute starter code and collect assignments on GitHub. This video walks you through the steps for setting up your first classroom and assignment."
"rTsfBAV7sOo":
  title: "How to set up individual assignments"
  provider: "youtube"
  description: "GitHub Classroom automates repository creation and access control, making it easy to distribute starter code and collect assignments on GitHub. This video walks you through the steps for setting up an individual assignment."
"-52quDR2QSc":
  title: "How to set up group assignments"
  provider: "youtube"
  description: "GitHub Classroom automates repository creation and access control, making it easy to distribute starter code and collect assignments on GitHub. This video walks students and teachers through the steps for setting up and participating in a group assignment."
